# === apt Operation Group ===

[operations.install_remote]
cmd_format = "apt install {pkgs}"

[operations.search_remote]
cmd_format = "apt search {pkgs}"

[operations.search_local]
cmd_format = "apt list --installed {pkgs}"

[operations.list_installed]
cmd_format = "apt list --installed"

[operations.find_file_owner_remote_with_regexp]
cmd_format = "apt-file search --regexp '{regexp}'"

[operations.force_refresh_repo_db]
cmd_format = "apt update --force-refresh-all"

[operations.download_source]
cmd_format = "apt source {pkgs}"

[operations.install_with_config]
cmd_format = "apt --config \"{config_path}\" install {pkgs}"

[operations.help]
cmd_format = "apt --help"

[operations.my_list_installed]
cmd_format = "apt list --installed --my"
final_cmd_format = "my-list-installed-apt"