# === 动作命令实现 ===
[operations.install_remote.apt]
cmd_format = "apt install {pkgs}"

[operations.search_remote.apt]
cmd_format = "apt search {pkgs}"

[operations.search_local.apt]
cmd_format = "apt list --installed {pkgs}"

[operations.list_installed.apt]
cmd_format = "apt list --installed"

[operations.find_file_owner_remote_with_regexp.apt-file]
cmd_format = "apt-file search --regexp {files}"

[operations.force_refresh_repo_db.apt]
cmd_format = "apt update --force-refresh-all"

[operations.download_source.apt]
cmd_format = "apt source {pkgs}"

[operations.install_with_config]
cmd_format = "apt install {pkgs} --config {config_path}"

[operations.help.apt]
cmd_format = "apt --help"